In [ ]:
import torch

lista = [[1,2,3],
         [4,5,6]]

tns = torch.Tensor(lista)
print(tns)
print(tns.dtype)

tns = torch.FloatTensor(lista)
print(tns)
print(tns.dtype)

tns = torch.DoubleTensor(lista)
print(tns)
print(tns.dtype)

tns = torch.LongTensor(lista)
print(tns)
print(tns.dtype)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)
torch.float64
tensor([[1, 2, 3],
        [4, 5, 6]])
torch.int64


# **Instanciar tensores de outras**

**A partir de arrays Numpy**

In [ ]:
import numpy as np

arr = np.random.rand(3,4)
tns = torch.from_numpy(arr)

#Preservando o tipo original dos dados
print(arr)
print(arr.dtype)

print(tns)
print(tns.dtype)

[[0.22856708 0.4275819  0.94388055 0.65830439]
 [0.62689111 0.62190951 0.35257311 0.11266098]
 [0.07372881 0.51845197 0.31193019 0.24588708]]
float64
tensor([[0.2286, 0.4276, 0.9439, 0.6583],
        [0.6269, 0.6219, 0.3526, 0.1127],
        [0.0737, 0.5185, 0.3119, 0.2459]], dtype=torch.float64)
torch.float64


**Tensores inicializados**

Essas funções recebem como parâmetro o tamanho de cada dimensão do  tensor

- torch.zeros()

- torch.ones()

- torch.randn()

In [ ]:
tns1 = torch.zeros(4,5)
tns2 = torch.ones(2,3)
tnsr = torch.randn(3,3)

print(tns1)
print(tns2)
print(tnsr)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[ 1.8504,  0.2037,  0.3416],
        [-0.7798, -1.4793, -0.7483],
        [-0.3860, -0.0956,  1.2539]])


**Tensor para array do numpy**

In [ ]:
arr = tns.data.numpy()
print(arr)
print(arr.dtype)

[[0.22856708 0.4275819  0.94388055 0.65830439]
 [0.62689111 0.62190951 0.35257311 0.11266098]
 [0.07372881 0.51845197 0.31193019 0.24588708]]
float64


# **Indexação**

In [ ]:
print(tnsr)
tnsr[0, 2] = -10

print(' ')
print(tnsr)

#Acessando as linhas 0 e 1
print(tnsr[0:2])

#Acessando a coluna 2
print(tnsr[:, 2])

#Acessando um elemento específico
print(tnsr[0,2])

tensor([[  1.8504,   0.2037, -10.0000],
        [ -0.7798,  -1.4793,  -0.7483],
        [ -0.3860,  -0.0956,   1.2539]])
 
tensor([[  1.8504,   0.2037, -10.0000],
        [ -0.7798,  -1.4793,  -0.7483],
        [ -0.3860,  -0.0956,   1.2539]])
tensor([[  1.8504,   0.2037, -10.0000],
        [ -0.7798,  -1.4793,  -0.7483]])
tensor([-10.0000,  -0.7483,   1.2539])
tensor(-10.)


# **Operações com tensores**

In [ ]:
tns = tnsr[0:2,:]
#Devem ter a mesma direção
print(tns)
print(tns + tns)

print(torch.mm(tns,tns.T))

tensor([[  1.8504,   0.2037, -10.0000],
        [ -0.7798,  -1.4793,  -0.7483]])
tensor([[  3.7008,   0.4075, -20.0000],
        [ -1.5597,  -2.9586,  -1.4967]])
tensor([[103.4655,   5.7389],
        [  5.7389,   3.3565]])


# **Função .size() e view()**

In [ ]:
tns = torch.randn(2,2,3)
print(tns)

#Dimensão do tensor
print(tns.size())

#Redimensionando o tensor
print(tns.view(4,3))

#Mantendo somente a primeira dimensão
print(tns.view(tns.size(0),-1))

tensor([[[-0.6371, -0.6412,  0.2289],
         [-0.1411,  2.1743, -1.2909]],

        [[ 0.2532,  1.3770,  0.2281],
         [-0.9224, -1.1945, -0.1884]]])
torch.Size([2, 2, 3])
tensor([[-0.6371, -0.6412,  0.2289],
        [-0.1411,  2.1743, -1.2909],
        [ 0.2532,  1.3770,  0.2281],
        [-0.9224, -1.1945, -0.1884]])
tensor([[-0.6371, -0.6412,  0.2289, -0.1411,  2.1743, -1.2909],
        [ 0.2532,  1.3770,  0.2281, -0.9224, -1.1945, -0.1884]])


# **GPU**

In [ ]:
import torch

tns = torch.randn(10)
if torch.cuda.is_available():
  device = torch.device('cuda')
else:
  device = torch.device('cpu')

print(device)

#Transferindo para a GPU, tenho que modificar nas configurações
tns = tns.to(device)
print(tns)

cpu
